version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: energy-trading-postgres
    environment:
      POSTGRES_DB: energy_trading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - energy-trading-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # Energy Trading API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy-trading-api
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/energy_trading
      RUST_LOG: info
      PORT: 3000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "3000:3000"
    networks:
      - energy-trading-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    
  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: energy-trading-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@energytrading.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - energy-trading-network
    depends_on:
      - postgres
    profiles:
      - admin

volumes:
  postgres_data:

networks:
  energy-trading-network:
    driver: bridge
