apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: energy-trading-api-pdb
  namespace: energy-trading
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: energy-trading-api
